spring:
  main:
    allow-circular-references: true
  #配置数据源
  datasource:
    druid-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xwhoa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
  mvc:
    static-path-pattern: /static/**
    #打开隐藏Http请求方式过滤器
    hiddenmethod:
      filter:
        enabled: true
    #静态资源放行

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML
    servlet:
      content-type: text/html

#服务器配置
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8888


#分页工具配置
pagehelper:
  #使用的数据库
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: admin
    password: 123456







